### ISSUE TITLE
Could you please provide the lookup table parameter for 128-channel LiDAR

### ISSUE THREAD

**Issue by Flandoe** [tiev-tongji/RingFalsNormal#2]
Hi~ My LiDAR is 128 -channel, and you just provide 32-channel velodyne LiDAR. Could you please provide the lookup table parameter for 128-channel LiDAR? Thank you.

**Comment by h-k8888** [comment]
> Hi~ My LiDAR is 128 -channel, and you just provide 32-channel velodyne LiDAR. Could you please provide the lookup table parameter for 128-channel LiDAR? Thank you.

Our code has been updated. Please pull down the latest code.
Following the readme, you can build your own lookup table.

**Comment by Flandoe** [comment]
It works well. Thank you.
