### ISSUE TITLE
关于运行

### ISSUE THREAD

**Issue by QiXueZhong** [tiev-tongji/RingFalsNormal#3]
你好呀，感谢开源这么棒的工作，我想问一下关于运行的问题，我用的是[NTU VIRAL](https://github.com/ntu-aris/ntu_viral_dataset)中的eee_03.bag数据，但是运行后仅有点云，并没有方向的Marker，请问这是为什么啊？编译运行还有什么需要注意的吗？
![c4ecde58f345f4c7ceb0bba6c279882](https://github.com/tiev-tongji/RingFalsNormal/assets/100745843/9c21b6b4-a386-410a-9e07-732e1e9f8f4d)

**Comment by h-k8888** [comment]
配置文件的 _**compute_table**_ 设置为true就好了，我在更新的时候忘记修改了。
你也可以重新pull一下仓库。
<img width="1723" alt="image" src="https://github.com/tiev-tongji/RingFalsNormal/assets/68782862/d82c4400-04c9-4942-b297-397392767311">
