### ISSUE TITLE
点云边缘处法线计算有误

### ISSUE THREAD

**Issue by Rogers34** [tiev-tongji/RingFalsNormal#4]
大佬你好，
非常感谢你分享的工作！
我有个问题想和你请教以下，像这种边缘处的点云法线计算的不准，不知你之前遇到过这个问题没有，有没有好的解决方法呢？
![snapshot01](https://github.com/tiev-tongji/RingFalsNormal/assets/28282833/4fada769-07c4-4ad7-a200-86bb5c24b732)
![snapshot00](https://github.com/tiev-tongji/RingFalsNormal/assets/28282833/3a36a2ae-1b6f-4f9c-af38-9f1d9c549419)

**Comment by h-k8888** [comment]
边缘处不符合深度接近的假设，所以此方法计算误差会比较大。
过滤邻域深度差异过大的点应该能一定程度上缓解这个问题。
